manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zephyr
      remote: zmkfirmware
      revision: v2.5.0+zmk-fixes+kim-fixes
      import: app/west.yml
  self:
    path: config
