manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ianmuninio
      url-base: https://github.com/ianmuninio
  projects:
    - name: zmk-zephyr
      remote: ianmuninio
      revision: v2.5.0+zmk-fixes
      import: app/west.yml
  self:
    path: config
